import type { CaseItem } from "@/types/crm";

export const mockCases: CaseItem[] = [
  {
    id: "case-001",
    caseNumber: "CS-2026-001847",
    accountId: "acc-001",
    accountName: "Bowen Basin Mining Corp",
    type: "Complaint",
    subType: "Billing Dispute",
    status: "In Progress",
    priority: "High",
    slaStatus: "At Risk",
    slaDeadline: "12/02/2026 17:00",
    slaTimeRemaining: "1d 14h",
    owner: "Priya Sharma",
    team: "Large Market Support",
    createdDate: "07/02/2026",
    updatedDate: "10/02/2026",
    description:
      "Customer is disputing the January invoice for NMI 3012345678. They believe the demand charges are incorrect based on their contracted rate schedule. Requesting a review of the metering data and recalculation of charges.",
    resolution: "",
    communications: [
      {
        id: "comm-001",
        type: "Email",
        direction: "Inbound",
        from: "j.whitfield@bowenbasin.com.au",
        to: "support@tallyenergy.com.au",
        subject: "RE: January Invoice Query - LM-0045721",
        body: "Hi Priya,\n\nFollowing up on our call yesterday. I've attached the meter data from our side which shows significantly different readings to what's on the invoice.\n\nOur demand peak for January was 2,450 kW but the invoice shows 3,100 kW. This doesn't align with our operational logs.\n\nCan you please escalate this to your metering team urgently? We need this resolved before the payment due date on 15/02.\n\nRegards,\nJames Whitfield\nEnergy Manager\nBowen Basin Mining Corp",
        timestamp: "10/02/2026 09:14",
        attachments: [
          {
            id: "att-001",
            name: "Meter_Data_Jan2026.xlsx",
            type: "spreadsheet",
            size: "245 KB",
            uploadedBy: "James Whitfield",
            uploadedDate: "10/02/2026",
          },
        ],
      },
      {
        id: "comm-002",
        type: "Email",
        direction: "Outbound",
        from: "p.sharma@tallyenergy.com.au",
        to: "j.whitfield@bowenbasin.com.au",
        subject: "RE: January Invoice Query - LM-0045721",
        body: "Hi James,\n\nThank you for providing the meter data. I've forwarded this to our metering team for comparison against our records.\n\nI've also requested a manual read from the network to verify the interval data. We should have the results within 24-48 hours.\n\nI'll keep you updated on progress.\n\nKind regards,\nPriya Sharma\nLarge Market Support",
        timestamp: "10/02/2026 10:30",
        attachments: [],
      },
      {
        id: "comm-003",
        type: "Email",
        direction: "Inbound",
        from: "j.whitfield@bowenbasin.com.au",
        to: "support@tallyenergy.com.au",
        subject: "January Invoice Query - LM-0045721",
        body: "Dear Support Team,\n\nI'm writing regarding our January 2026 invoice for account LM-0045721. The demand charges appear significantly higher than expected based on our contracted rate schedule.\n\nPlease investigate and provide a breakdown of the metering data used for the calculation.\n\nRegards,\nJames Whitfield",
        timestamp: "07/02/2026 14:22",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-001",
        type: "Email Received",
        description: "Follow-up email received from James Whitfield with meter data attachment",
        user: "System",
        timestamp: "10/02/2026 09:14",
      },
      {
        id: "act-002",
        type: "Email Sent",
        description: "Response sent to customer confirming metering team review",
        user: "Priya Sharma",
        timestamp: "10/02/2026 10:30",
      },
      {
        id: "act-003",
        type: "Assignment",
        description: "Case assigned to Priya Sharma from queue",
        user: "Priya Sharma",
        timestamp: "07/02/2026 15:00",
      },
      {
        id: "act-004",
        type: "Status Change",
        description: "Status changed from New to In Progress",
        user: "Priya Sharma",
        timestamp: "07/02/2026 15:00",
        metadata: { from: "New", to: "In Progress" },
      },
      {
        id: "act-005",
        type: "Created",
        description: "Case created from inbound email",
        user: "System",
        timestamp: "07/02/2026 14:22",
      },
    ],
    attachments: [
      {
        id: "att-001",
        name: "Meter_Data_Jan2026.xlsx",
        type: "spreadsheet",
        size: "245 KB",
        uploadedBy: "James Whitfield",
        uploadedDate: "10/02/2026",
      },
      {
        id: "att-002",
        name: "Invoice_Jan2026_LM0045721.pdf",
        type: "pdf",
        size: "1.2 MB",
        uploadedBy: "System",
        uploadedDate: "07/02/2026",
      },
    ],
    relatedCases: ["CS-2026-001745", "CS-2026-001882"],
  },
  {
    id: "case-002",
    caseNumber: "CS-2026-001832",
    accountId: "acc-002",
    accountName: "Gladstone Aluminium Smelter",
    type: "EWR",
    subType: "Meter Replacement",
    status: "Pending",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "20/02/2026 17:00",
    slaTimeRemaining: "10d 8h",
    owner: "Daniel Cooper",
    team: "Large Market Support",
    createdDate: "03/02/2026",
    updatedDate: "08/02/2026",
    description:
      "Embedded works request for meter replacement at NMI 3098765434. Current CT meter is due for scheduled replacement as per the compliance programme. Network provider has been engaged.",
    resolution: "",
    communications: [
      {
        id: "comm-004",
        type: "Email",
        direction: "Outbound",
        from: "d.cooper@tallyenergy.com.au",
        to: "m.torres@gladstone-aluminium.com.au",
        subject: "EWR Update - Meter Replacement NMI 3098765434",
        body: "Hi Michael,\n\nJust a quick update on the meter replacement. Ergon has confirmed the site visit for 18/02/2026 between 08:00 and 12:00.\n\nPlease ensure site access is available and a representative can meet the technician at the main gate.\n\nRegards,\nDaniel Cooper",
        timestamp: "08/02/2026 11:45",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-006",
        type: "Email Sent",
        description: "Site visit confirmation sent to customer",
        user: "Daniel Cooper",
        timestamp: "08/02/2026 11:45",
      },
      {
        id: "act-007",
        type: "Status Change",
        description: "Status changed from In Progress to Pending",
        user: "Daniel Cooper",
        timestamp: "06/02/2026 09:00",
        metadata: { from: "In Progress", to: "Pending" },
      },
      {
        id: "act-008",
        type: "Created",
        description: "EWR created for scheduled meter replacement",
        user: "Daniel Cooper",
        timestamp: "03/02/2026 10:15",
      },
    ],
    attachments: [
      {
        id: "att-003",
        name: "EWR_Form_3098765434.pdf",
        type: "pdf",
        size: "890 KB",
        uploadedBy: "Daniel Cooper",
        uploadedDate: "03/02/2026",
      },
    ],
    relatedCases: ["CS-2026-001750", "CS-2026-001860"],
    pendingReason: "3rd Party",
  },
  {
    id: "case-003",
    caseNumber: "CS-2026-001790",
    accountId: "acc-003",
    accountName: "Mackay Sugar Mill Operations",
    type: "Enquiry",
    subType: "Rate Review",
    status: "New",
    priority: "Low",
    slaStatus: "On Track",
    slaDeadline: "17/02/2026 17:00",
    slaTimeRemaining: "7d 2h",
    owner: "Unassigned",
    team: "Large Market Support",
    createdDate: "05/02/2026",
    updatedDate: "05/02/2026",
    description:
      "Customer requesting a review of their current rate schedule ahead of contract renewal in September 2027. They want to explore green energy options and potential for PPA arrangements.",
    resolution: "",
    communications: [
      {
        id: "comm-005",
        type: "Email",
        direction: "Inbound",
        from: "d.patterson@mackaysugar.com.au",
        to: "support@tallyenergy.com.au",
        subject: "Rate Schedule Review Request - LM-0046102",
        body: "Dear Tally Energy Team,\n\nWe're looking to review our current rate schedule and explore options for our upcoming contract renewal. Specifically interested in:\n\n1. Green energy certificate options\n2. PPA arrangements with local solar farms\n3. Time-of-use rate optimisation\n\nCould someone from your large market team arrange a meeting to discuss?\n\nBest regards,\nDavid Patterson",
        timestamp: "05/02/2026 08:30",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-009",
        type: "Created",
        description: "Case created from inbound email",
        user: "System",
        timestamp: "05/02/2026 08:30",
      },
    ],
    attachments: [],
    relatedCases: ["CS-2026-001870", "CS-2026-001900"],
  },
  {
    id: "case-004",
    caseNumber: "CS-2026-001855",
    accountId: "acc-004",
    accountName: "Brisbane Convention Centre",
    type: "Complaint",
    subType: "Service Quality",
    status: "In Progress",
    priority: "Critical",
    slaStatus: "Breached",
    slaDeadline: "09/02/2026 12:00",
    slaTimeRemaining: "Overdue by 22h",
    owner: "Priya Sharma",
    team: "Large Market Support",
    createdDate: "08/02/2026",
    updatedDate: "10/02/2026",
    description:
      "Customer experienced two unplanned outages in the past week affecting event operations. Requesting urgent investigation and compensation for lost revenue from cancelled bookings.",
    resolution: "",
    communications: [
      {
        id: "comm-006",
        type: "Phone",
        direction: "Inbound",
        from: "Amanda Foster",
        to: "Priya Sharma",
        subject: "Urgent: Repeated Outages at Convention Centre",
        loggedBy: "Priya Sharma",
        body: "Phone call received from Amanda Foster regarding second power outage in 5 days. Convention centre had to cancel a corporate gala dinner affecting 350 guests. Customer extremely dissatisfied and requesting immediate escalation to management. Mentioned potential ombudsman complaint if not resolved promptly.",
        timestamp: "10/02/2026 08:15",
        attachments: [],
      },
      {
        id: "comm-007",
        type: "Email",
        direction: "Inbound",
        from: "a.foster@brisbanecc.com.au",
        to: "support@tallyenergy.com.au",
        subject: "URGENT: Second Power Outage - Requesting Immediate Action",
        body: "Dear Tally Energy,\n\nThis is completely unacceptable. We have now experienced two unplanned outages within 5 days:\n\n- 03/02 at 18:45 - Power loss for 2.5 hours during wedding reception\n- 08/02 at 14:30 - Power loss for 45 minutes during corporate event setup\n\nWe have lost significant revenue and our reputation with clients is being damaged. We require:\n\n1. Immediate root cause analysis\n2. A guaranteed remediation plan\n3. Compensation for lost revenue (estimated $85,000)\n\nIf this is not resolved within 24 hours, we will be filing a formal complaint with the Energy Ombudsman.\n\nAmanda Foster\nFacilities Manager",
        timestamp: "08/02/2026 16:20",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-010",
        type: "Email Received",
        description: "Urgent complaint email received regarding repeated outages",
        user: "System",
        timestamp: "08/02/2026 16:20",
      },
      {
        id: "act-011",
        type: "SLA Update",
        description: "SLA breached — response deadline exceeded",
        user: "System",
        timestamp: "09/02/2026 12:00",
      },
      {
        id: "act-012",
        type: "Assignment",
        description: "Case escalated and assigned to Priya Sharma",
        user: "Team Lead",
        timestamp: "09/02/2026 08:30",
      },
      {
        id: "act-013",
        type: "Created",
        description: "Case created from urgent inbound email",
        user: "System",
        timestamp: "08/02/2026 16:20",
      },
    ],
    attachments: [],
    relatedCases: ["CS-2026-001890", "CS-2026-001910"],
  },
  {
    id: "case-005",
    caseNumber: "CS-2026-001720",
    accountId: "acc-005",
    accountName: "Townsville Port Authority",
    type: "Onboarding",
    subType: "New Connection",
    status: "Resolved",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "15/02/2026 17:00",
    slaTimeRemaining: "N/A",
    owner: "Daniel Cooper",
    team: "Large Market Support",
    createdDate: "20/01/2026",
    updatedDate: "09/02/2026",
    description:
      "New meter connection for expansion to berth 14. All network applications and metering installations completed. Awaiting final energisation confirmation.",
    resolution:
      "New NMI 3045678903 successfully energised on 09/02/2026. Meter reading confirmed at 0 kWh. Customer notified and billing configuration set up for the new site.",
    communications: [
      {
        id: "comm-008",
        type: "Email",
        direction: "Outbound",
        from: "d.cooper@tallyenergy.com.au",
        to: "k.mitchell@townsvilleport.com.au",
        subject: "Connection Complete - NMI 3045678903 Energised",
        body: "Hi Karen,\n\nGreat news — the new connection at Berth 14 has been successfully energised. NMI 3045678903 is now active and the initial meter reading has been confirmed at 0 kWh.\n\nBilling will commence from the next billing cycle. Please let me know if you have any questions.\n\nRegards,\nDaniel Cooper",
        timestamp: "09/02/2026 14:00",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-014",
        type: "Status Change",
        description: "Status changed from In Progress to Resolved",
        user: "Daniel Cooper",
        timestamp: "09/02/2026 14:00",
        metadata: { from: "In Progress", to: "Resolved" },
      },
      {
        id: "act-015",
        type: "Email Sent",
        description: "Completion notification sent to customer",
        user: "Daniel Cooper",
        timestamp: "09/02/2026 14:00",
      },
      {
        id: "act-016",
        type: "Created",
        description: "Onboarding case created for new berth 14 connection",
        user: "Daniel Cooper",
        timestamp: "20/01/2026 09:00",
      },
    ],
    attachments: [
      {
        id: "att-004",
        name: "Network_Application_B14.pdf",
        type: "pdf",
        size: "2.1 MB",
        uploadedBy: "Daniel Cooper",
        uploadedDate: "20/01/2026",
      },
      {
        id: "att-005",
        name: "Energisation_Certificate.pdf",
        type: "pdf",
        size: "540 KB",
        uploadedBy: "Daniel Cooper",
        uploadedDate: "09/02/2026",
      },
    ],
    relatedCases: [],
  },
  {
    id: "case-006",
    caseNumber: "CS-2026-001860",
    accountId: "acc-002",
    accountName: "Gladstone Aluminium Smelter",
    type: "Dunning",
    subType: "Payment Reminder",
    status: "New",
    priority: "High",
    slaStatus: "On Track",
    slaDeadline: "14/02/2026 17:00",
    slaTimeRemaining: "4d 6h",
    owner: "Unassigned",
    team: "Collections",
    createdDate: "10/02/2026",
    updatedDate: "10/02/2026",
    description:
      "Automated dunning workflow triggered for overdue gas invoice. Payment of $312,000 was due on 31/01/2026. Second reminder to be issued.",
    resolution: "",
    communications: [],
    activities: [
      {
        id: "act-017",
        type: "Created",
        description: "Dunning case auto-created for overdue gas invoice",
        user: "System",
        timestamp: "10/02/2026 06:00",
      },
    ],
    attachments: [],
    relatedCases: ["CS-2026-001750", "CS-2026-001832"],
  },
  {
    id: "case-007",
    caseNumber: "CS-2026-001745",
    accountId: "acc-001",
    accountName: "Bowen Basin Mining Corp",
    type: "Enquiry",
    subType: "Contract Amendment",
    status: "Closed",
    priority: "Low",
    slaStatus: "On Track",
    slaDeadline: "30/01/2026 17:00",
    slaTimeRemaining: "N/A",
    owner: "Priya Sharma",
    team: "Large Market Support",
    createdDate: "22/01/2026",
    updatedDate: "30/01/2026",
    description:
      "Customer requested amendment to contract terms for demand response participation programme.",
    resolution:
      "Contract amendment processed. Updated terms include demand response participation clause with agreed incentive structure. Customer signed updated agreement on 29/01/2026.",
    communications: [],
    activities: [
      {
        id: "act-018",
        type: "Status Change",
        description: "Status changed from Resolved to Closed",
        user: "Priya Sharma",
        timestamp: "30/01/2026 16:30",
        metadata: { from: "Resolved", to: "Closed" },
      },
      {
        id: "act-019",
        type: "Created",
        description: "Enquiry case created for contract amendment request",
        user: "Priya Sharma",
        timestamp: "22/01/2026 11:00",
      },
    ],
    attachments: [],
    relatedCases: ["CS-2026-001847", "CS-2026-001882"],
  },
  {
    id: "case-008",
    caseNumber: "CS-2026-001870",
    accountId: "acc-003",
    accountName: "Mackay Sugar Mill Operations",
    type: "EWR",
    subType: "Network Upgrade",
    status: "In Progress",
    priority: "High",
    slaStatus: "At Risk",
    slaDeadline: "13/02/2026 17:00",
    slaTimeRemaining: "3d 5h",
    owner: "Daniel Cooper",
    team: "Large Market Support",
    createdDate: "01/02/2026",
    updatedDate: "09/02/2026",
    description:
      "Network augmentation required for increased capacity to support new crushing line. Transformer upgrade from 5MVA to 10MVA at NMI 3054321098.",
    resolution: "",
    communications: [
      {
        id: "comm-009",
        type: "Email",
        direction: "Outbound",
        from: "d.cooper@tallyenergy.com.au",
        to: "d.patterson@mackaysugar.com.au",
        subject: "Network Upgrade Progress - NMI 3054321098",
        body: "Hi David,\n\nUpdate on the transformer upgrade:\n\n- Network design approval: Received 07/02\n- Equipment procurement: Ordered, ETA 25/02\n- Scheduled outage window: TBC\n\nI'll confirm the outage schedule once Ergon provides available dates.\n\nRegards,\nDaniel",
        timestamp: "09/02/2026 15:30",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-020",
        type: "Email Sent",
        description: "Progress update sent to customer",
        user: "Daniel Cooper",
        timestamp: "09/02/2026 15:30",
      },
      {
        id: "act-021",
        type: "Created",
        description: "EWR created for transformer upgrade",
        user: "Daniel Cooper",
        timestamp: "01/02/2026 13:00",
      },
    ],
    attachments: [
      {
        id: "att-006",
        name: "Network_Design_Approval.pdf",
        type: "pdf",
        size: "3.4 MB",
        uploadedBy: "Daniel Cooper",
        uploadedDate: "07/02/2026",
      },
    ],
    relatedCases: [],
  },
  // ── Additional cases for list-view coverage ──────────────────────────────
  {
    id: "case-009",
    caseNumber: "CS-2026-001882",
    accountId: "acc-001",
    accountName: "Bowen Basin Mining Corp",
    type: "Enquiry",
    subType: "Tariff Information",
    status: "In Progress",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "18/02/2026 17:00",
    slaTimeRemaining: "7d 10h",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "10/02/2026",
    updatedDate: "11/02/2026",
    description:
      "Customer requesting detailed tariff comparison for NMI 3012345678 to evaluate whether a time-of-use structure would reduce costs during off-peak crushing operations.",
    resolution: "",
    communications: [
      {
        id: "comm-010",
        type: "Email",
        direction: "Inbound",
        from: "j.whitfield@bowenbasin.com.au",
        to: "support@tallyenergy.com.au",
        subject: "Tariff comparison request",
        body: "Hi team,\n\nCould you provide a comparison of our current flat rate vs a TOU tariff? Our off-peak usage is significant and we'd like to understand savings potential.\n\nRegards,\nJames Whitfield",
        timestamp: "10/02/2026 10:00",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-022",
        type: "Assignment",
        description: "Case assigned to John Smith",
        user: "John Smith",
        timestamp: "10/02/2026 11:00",
      },
      {
        id: "act-023",
        type: "Created",
        description: "Case created from inbound email",
        user: "System",
        timestamp: "10/02/2026 10:00",
      },
    ],
    attachments: [],
    relatedCases: [],
  },
  {
    id: "case-010",
    caseNumber: "CS-2026-001890",
    accountId: "acc-004",
    accountName: "Brisbane Convention Centre",
    type: "Complaint",
    subType: "Billing Error",
    status: "New",
    priority: "High",
    slaStatus: "On Track",
    slaDeadline: "16/02/2026 17:00",
    slaTimeRemaining: "5d 12h",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "11/02/2026",
    updatedDate: "11/02/2026",
    description:
      "Customer reporting duplicate charges on the February invoice. Two line items for the same NMI appear on the statement with identical amounts. Requesting immediate correction.",
    resolution: "",
    communications: [
      {
        id: "comm-011",
        type: "Email",
        direction: "Inbound",
        from: "a.foster@brisbanecc.com.au",
        to: "support@tallyenergy.com.au",
        subject: "Duplicate charges on Feb invoice",
        body: "Hi,\n\nOur February invoice shows two identical charges of $14,200 for NMI 3067890123. This looks like a duplicate. Please investigate and issue a corrected invoice.\n\nThanks,\nAmanda Foster",
        timestamp: "11/02/2026 09:00",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-024",
        type: "Created",
        description: "Case created from inbound email",
        user: "System",
        timestamp: "11/02/2026 09:00",
      },
    ],
    attachments: [],
    relatedCases: ["CS-2026-001855"],
  },
  {
    id: "case-011",
    caseNumber: "CS-2026-001895",
    accountId: "acc-005",
    accountName: "Townsville Port Authority",
    type: "EWR",
    subType: "Solar Installation",
    status: "Pending",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "28/02/2026 17:00",
    slaTimeRemaining: "17d 8h",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "06/02/2026",
    updatedDate: "10/02/2026",
    description:
      "EWR for rooftop solar installation at Berth 14 office building. 150kW system. Awaiting network study results from Ergon before proceeding with installation approval.",
    resolution: "",
    communications: [],
    activities: [
      {
        id: "act-025",
        type: "Status Change",
        description: "Status changed from In Progress to Pending — awaiting network study",
        user: "John Smith",
        timestamp: "10/02/2026 14:00",
        metadata: { from: "In Progress", to: "Pending" },
      },
      {
        id: "act-026",
        type: "Created",
        description: "EWR created for solar installation",
        user: "John Smith",
        timestamp: "06/02/2026 09:30",
      },
    ],
    attachments: [
      {
        id: "att-007",
        name: "Solar_Design_150kW_B14.pdf",
        type: "pdf",
        size: "5.8 MB",
        uploadedBy: "John Smith",
        uploadedDate: "06/02/2026",
      },
    ],
    relatedCases: ["CS-2026-001720", "CS-2026-001780"],
    pendingReason: "On Hold",
  },
  {
    id: "case-012",
    caseNumber: "CS-2026-001750",
    accountId: "acc-002",
    accountName: "Gladstone Aluminium Smelter",
    type: "Enquiry",
    subType: "Account Information",
    status: "Closed",
    priority: "Low",
    slaStatus: "On Track",
    slaDeadline: "03/02/2026 17:00",
    slaTimeRemaining: "N/A",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "27/01/2026",
    updatedDate: "02/02/2026",
    description:
      "Customer requested updated statement of account for their finance team's quarterly reporting. Sent consolidated statement covering all three NMIs.",
    resolution:
      "Consolidated statement for NMIs 3098765432, 3098765433, and 3098765434 generated and emailed to customer on 02/02/2026. No outstanding issues.",
    communications: [],
    activities: [
      {
        id: "act-027",
        type: "Status Change",
        description: "Status changed from Resolved to Closed",
        user: "John Smith",
        timestamp: "02/02/2026 16:00",
        metadata: { from: "Resolved", to: "Closed" },
      },
      {
        id: "act-028",
        type: "Created",
        description: "Enquiry created for statement of account request",
        user: "John Smith",
        timestamp: "27/01/2026 10:00",
      },
    ],
    attachments: [],
    relatedCases: ["CS-2026-001832", "CS-2026-001860"],
  },
  {
    id: "case-013",
    caseNumber: "CS-2026-001900",
    accountId: "acc-003",
    accountName: "Mackay Sugar Mill Operations",
    type: "Onboarding",
    subType: "Meter Installation",
    status: "New",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "25/02/2026 17:00",
    slaTimeRemaining: "14d 6h",
    owner: "Unassigned",
    team: "Large Market Support",
    createdDate: "11/02/2026",
    updatedDate: "11/02/2026",
    description:
      "New meter installation required for additional processing shed. Customer has submitted the electrical works request form. Awaiting assignment to field operations team.",
    resolution: "",
    communications: [
      {
        id: "comm-012",
        type: "Email",
        direction: "Inbound",
        from: "d.patterson@mackaysugar.com.au",
        to: "support@tallyenergy.com.au",
        subject: "New meter for processing shed B",
        body: "Hi team,\n\nPlease find attached the EWR form for a new meter at our processing shed B. We need this operational by end of March.\n\nRegards,\nDavid Patterson",
        timestamp: "11/02/2026 07:45",
        attachments: [
          {
            id: "att-008",
            name: "EWR_Processing_Shed_B.pdf",
            type: "pdf",
            size: "1.1 MB",
            uploadedBy: "David Patterson",
            uploadedDate: "11/02/2026",
          },
        ],
      },
    ],
    activities: [
      {
        id: "act-029",
        type: "Created",
        description: "Case created from inbound email with attachment",
        user: "System",
        timestamp: "11/02/2026 07:45",
      },
    ],
    attachments: [
      {
        id: "att-008",
        name: "EWR_Processing_Shed_B.pdf",
        type: "pdf",
        size: "1.1 MB",
        uploadedBy: "David Patterson",
        uploadedDate: "11/02/2026",
      },
    ],
    relatedCases: [],
  },
  {
    id: "case-014",
    caseNumber: "CS-2026-001905",
    accountId: "acc-001",
    accountName: "Bowen Basin Mining Corp",
    type: "Dunning",
    subType: "Final Notice",
    status: "In Progress",
    priority: "Critical",
    slaStatus: "At Risk",
    slaDeadline: "13/02/2026 12:00",
    slaTimeRemaining: "1d 23h",
    owner: "John Smith",
    team: "Collections",
    createdDate: "09/02/2026",
    updatedDate: "11/02/2026",
    description:
      "Final notice stage for overdue electricity invoice. Amount owing: $187,500. Previous reminders sent on 20/01 and 03/02. Customer has been contacted by phone; payment plan under discussion.",
    resolution: "",
    communications: [
      {
        id: "comm-013",
        type: "Phone",
        direction: "Outbound",
        from: "John Smith",
        to: "James Whitfield",
        subject: "Payment plan discussion — final notice",
        loggedBy: "John Smith",
        body: "Called James Whitfield to discuss the overdue balance. Customer acknowledged the debt and proposed a payment plan of 3 monthly instalments. Awaiting finance team approval of the plan before confirming with the customer.",
        timestamp: "11/02/2026 14:30",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-030",
        type: "Comment",
        description: "Customer proposed 3-month payment plan. Sent to finance for approval.",
        user: "John Smith",
        timestamp: "11/02/2026 14:45",
      },
      {
        id: "act-031",
        type: "Created",
        description: "Final notice dunning case auto-created",
        user: "System",
        timestamp: "09/02/2026 06:00",
      },
    ],
    attachments: [],
    relatedCases: ["CS-2026-001860"],
  },
  {
    id: "case-015",
    caseNumber: "CS-2026-001910",
    accountId: "acc-004",
    accountName: "Brisbane Convention Centre",
    type: "Enquiry",
    subType: "Green Energy Options",
    status: "New",
    priority: "Low",
    slaStatus: "On Track",
    slaDeadline: "20/02/2026 17:00",
    slaTimeRemaining: "9d 4h",
    owner: "Unassigned",
    team: "Large Market Support",
    createdDate: "11/02/2026",
    updatedDate: "11/02/2026",
    description:
      "Customer interested in carbon offset programme and GreenPower options for their next contract period. Sustainability initiative driven by venue marketing requirements.",
    resolution: "",
    communications: [
      {
        id: "comm-014",
        type: "Email",
        direction: "Inbound",
        from: "t.richards@brisbanecc.com.au",
        to: "support@tallyenergy.com.au",
        subject: "Green energy and carbon offset enquiry",
        body: "Dear Tally Energy,\n\nAs part of our sustainability commitment, we'd like to explore GreenPower and carbon offset options for our next contract. Could someone provide an overview of available programmes and indicative pricing?\n\nKind regards,\nTom Richards\nCFO",
        timestamp: "11/02/2026 11:15",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-032",
        type: "Created",
        description: "Case created from inbound email",
        user: "System",
        timestamp: "11/02/2026 11:15",
      },
    ],
    attachments: [],
    relatedCases: [],
  },
  {
    id: "case-016",
    caseNumber: "CS-2026-001780",
    accountId: "acc-005",
    accountName: "Townsville Port Authority",
    type: "Complaint",
    subType: "Delayed Response",
    status: "Resolved",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "08/02/2026 17:00",
    slaTimeRemaining: "N/A",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "01/02/2026",
    updatedDate: "07/02/2026",
    description:
      "Customer complained about a 5-day delay in responding to their initial meter query. Investigated and found the email was routed to the wrong queue. Process corrected.",
    resolution:
      "Root cause identified as incorrect email routing rule. Rule updated to ensure Townsville Port queries route to Large Market Support. Customer accepted apology and is satisfied with the corrective action.",
    communications: [],
    activities: [
      {
        id: "act-033",
        type: "Status Change",
        description: "Status changed from In Progress to Resolved",
        user: "John Smith",
        timestamp: "07/02/2026 15:00",
        metadata: { from: "In Progress", to: "Resolved" },
      },
      {
        id: "act-034",
        type: "Created",
        description: "Complaint case created",
        user: "John Smith",
        timestamp: "01/02/2026 08:00",
      },
    ],
    attachments: [],
    relatedCases: [],
  },
];

export function getCaseById(id: string): CaseItem | undefined {
  return mockCases.find((c) => c.id === id);
}

export function getCaseByCaseNumber(caseNumber: string): CaseItem | undefined {
  return mockCases.find((c) => c.caseNumber === caseNumber);
}

export function getCasesBySLA(status: string): CaseItem[] {
  return mockCases.filter((c) => c.slaStatus === status);
}
