import type { Opportunity } from "@/types/crm";

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-001",
    name: "Bowen Basin — 3-Year Extension",
    accountId: "acc-001",
    accountName: "Bowen Basin Mining Corp",
    stage: "Negotiation",
    value: 4500000,
    probability: 75,
    owner: "Rachel Wong",
    expectedCloseDate: "30/03/2026",
    createdDate: "15/11/2025",
    updatedDate: "09/02/2026",
    description:
      "3-year contract extension with expanded scope to include demand response programme and green energy certificates.",
    competition: "Origin Energy, AGL",
    energyType: "Electricity",
    annualVolume: "12,500,000 kWh",
    contractTerm: "36 months",
    contacts: [
      {
        id: "con-001",
        name: "James Whitfield",
        role: "Energy Manager",
        email: "j.whitfield@bowenbasin.com.au",
        phone: "07 4921 3300",
        isPrimary: true,
      },
      {
        id: "con-002",
        name: "Sarah Chen",
        role: "Finance Director",
        email: "s.chen@bowenbasin.com.au",
        phone: "07 4921 3301",
        isPrimary: false,
      },
    ],
    activities: [
      {
        id: "act-p001",
        type: "Comment",
        description: "Final pricing submitted. Customer reviewing with board.",
        user: "Rachel Wong",
        timestamp: "09/02/2026 11:00",
      },
      {
        id: "act-p002",
        type: "Status Change",
        description: "Stage moved from Proposal to Negotiation",
        user: "Rachel Wong",
        timestamp: "05/02/2026 14:30",
        metadata: { from: "Proposal", to: "Negotiation" },
      },
    ],
    attachments: [
      {
        id: "att-p001",
        name: "Proposal_BowenBasin_2026.pdf",
        type: "pdf",
        size: "4.2 MB",
        uploadedBy: "Rachel Wong",
        uploadedDate: "01/02/2026",
      },
    ],
    docuSignStatus: "Not Started",
    linkedQuotes: [
      {
        id: "q-001",
        name: "Quote — 3yr Fixed + DR",
        value: 4500000,
        status: "Sent",
        createdDate: "01/02/2026",
        expiryDate: "01/03/2026",
      },
      {
        id: "q-002",
        name: "Quote — 3yr Variable",
        value: 4200000,
        status: "Rejected",
        createdDate: "20/01/2026",
        expiryDate: "20/02/2026",
      },
    ],
  },
  {
    id: "opp-002",
    name: "Gladstone Aluminium — Gas Supply",
    accountId: "acc-002",
    accountName: "Gladstone Aluminium Smelter",
    stage: "Proposal",
    value: 2800000,
    probability: 50,
    owner: "Rachel Wong",
    expectedCloseDate: "15/04/2026",
    createdDate: "10/12/2025",
    updatedDate: "07/02/2026",
    description:
      "Standalone gas supply proposal for the smelter operations. Currently supplied by a competitor. Opportunity to bundle with existing electricity contract.",
    competition: "Shell Energy",
    energyType: "Gas",
    annualVolume: "8,200,000 MJ",
    contractTerm: "24 months",
    contacts: [
      {
        id: "con-003",
        name: "Michael Torres",
        role: "Procurement Manager",
        email: "m.torres@gladstone-aluminium.com.au",
        phone: "07 4972 1100",
        isPrimary: true,
      },
    ],
    activities: [
      {
        id: "act-p003",
        type: "Comment",
        description: "Proposal document under legal review. Expected sign-off this week.",
        user: "Rachel Wong",
        timestamp: "07/02/2026 16:00",
      },
    ],
    attachments: [],
    docuSignStatus: "Not Started",
    linkedQuotes: [
      {
        id: "q-003",
        name: "Quote — Gas 24m Fixed",
        value: 2800000,
        status: "Draft",
        createdDate: "07/02/2026",
        expiryDate: "07/03/2026",
      },
    ],
  },
  {
    id: "opp-003",
    name: "Brisbane Convention Centre — Renewal",
    accountId: "acc-004",
    accountName: "Brisbane Convention Centre",
    stage: "Qualification",
    value: 850000,
    probability: 30,
    owner: "Marcus Lee",
    expectedCloseDate: "28/02/2027",
    createdDate: "05/01/2026",
    updatedDate: "06/02/2026",
    description:
      "Early engagement for contract renewal. Customer exploring sustainability options including carbon offset programmes. Current outage issues may affect renewal sentiment.",
    competition: "EnergyAustralia",
    energyType: "Dual Fuel",
    annualVolume: "3,200,000 kWh / 1,450,000 MJ",
    contractTerm: "36 months",
    contacts: [
      {
        id: "con-006",
        name: "Amanda Foster",
        role: "Facilities Manager",
        email: "a.foster@brisbanecc.com.au",
        phone: "07 3308 3000",
        isPrimary: true,
      },
      {
        id: "con-007",
        name: "Tom Richards",
        role: "CFO",
        email: "t.richards@brisbanecc.com.au",
        phone: "07 3308 3001",
        isPrimary: false,
      },
    ],
    activities: [
      {
        id: "act-p004",
        type: "Comment",
        description: "Need to address outage complaints before progressing. Risk of churn.",
        user: "Marcus Lee",
        timestamp: "06/02/2026 09:30",
      },
    ],
    attachments: [],
    docuSignStatus: "Not Started",
    linkedQuotes: [],
  },
  {
    id: "opp-004",
    name: "Townsville Port — Expansion Sites",
    accountId: "acc-005",
    accountName: "Townsville Port Authority",
    stage: "Discovery",
    value: 1200000,
    probability: 15,
    owner: "Marcus Lee",
    expectedCloseDate: "30/06/2026",
    createdDate: "01/02/2026",
    updatedDate: "08/02/2026",
    description:
      "New supply opportunity for three planned expansion berths. Port authority has approved capital works and electricity supply will be required from Q3 2026.",
    competition: "Ergon Retail",
    energyType: "Electricity",
    annualVolume: "4,500,000 kWh (estimated)",
    contractTerm: "48 months",
    contacts: [
      {
        id: "con-008",
        name: "Karen Mitchell",
        role: "Infrastructure Manager",
        email: "k.mitchell@townsvilleport.com.au",
        phone: "07 4781 1500",
        isPrimary: true,
      },
    ],
    activities: [
      {
        id: "act-p005",
        type: "Created",
        description: "Opportunity created from onboarding case lead",
        user: "Marcus Lee",
        timestamp: "01/02/2026 10:00",
      },
    ],
    attachments: [],
    docuSignStatus: "Not Started",
    linkedQuotes: [],
  },
  {
    id: "opp-005",
    name: "Mackay Sugar — Green PPA",
    accountId: "acc-003",
    accountName: "Mackay Sugar Mill Operations",
    stage: "Discovery",
    value: 2100000,
    probability: 10,
    owner: "Rachel Wong",
    expectedCloseDate: "30/09/2026",
    createdDate: "06/02/2026",
    updatedDate: "06/02/2026",
    description:
      "Early-stage opportunity for a Power Purchase Agreement with a local solar farm. Customer interested in green energy options as part of their sustainability programme.",
    competition: "None identified",
    energyType: "Electricity",
    annualVolume: "8,750,000 kWh",
    contractTerm: "60 months",
    contacts: [
      {
        id: "con-005",
        name: "David Patterson",
        role: "Operations Director",
        email: "d.patterson@mackaysugar.com.au",
        phone: "07 4944 2500",
        isPrimary: true,
      },
    ],
    activities: [
      {
        id: "act-p006",
        type: "Created",
        description: "Opportunity created from rate review enquiry",
        user: "Rachel Wong",
        timestamp: "06/02/2026 14:00",
      },
    ],
    attachments: [],
    docuSignStatus: "Not Started",
    linkedQuotes: [],
  },
  {
    id: "opp-006",
    name: "Gladstone Aluminium — Elec Renewal",
    accountId: "acc-002",
    accountName: "Gladstone Aluminium Smelter",
    stage: "Closed Won",
    value: 5200000,
    probability: 100,
    owner: "Rachel Wong",
    expectedCloseDate: "15/12/2025",
    createdDate: "01/08/2025",
    updatedDate: "15/12/2025",
    description:
      "Electricity contract renewal for all three NMIs. Successfully retained against competitive bids from Origin and AGL.",
    competition: "Origin Energy, AGL",
    energyType: "Electricity",
    annualVolume: "45,000,000 kWh",
    contractTerm: "24 months",
    contacts: [
      {
        id: "con-003",
        name: "Michael Torres",
        role: "Procurement Manager",
        email: "m.torres@gladstone-aluminium.com.au",
        phone: "07 4972 1100",
        isPrimary: true,
      },
    ],
    activities: [],
    attachments: [],
    docuSignStatus: "Completed",
    linkedQuotes: [
      {
        id: "q-004",
        name: "Quote — Elec 24m Fixed",
        value: 5200000,
        status: "Accepted",
        createdDate: "01/11/2025",
        expiryDate: "01/12/2025",
      },
    ],
  },
];

export function getOpportunityById(id: string): Opportunity | undefined {
  return mockOpportunities.find((o) => o.id === id);
}

export function getOpportunitiesByStage(stage: string): Opportunity[] {
  return mockOpportunities.filter((o) => o.stage === stage);
}

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-AU", {
    style: "currency",
    currency: "AUD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}
